FROM node:lts-buster
WORKDIR /app
COPY src /app/src
COPY package.json /app/package.json
COPY tsconfig.json /app/tsconfig.json
COPY .env /app/.env
RUN npm install && npm run build
ENTRYPOINT [ "npm", "run", "start:watch" ]